### ISSUE TITLE
Indicate when lakeshore is not connected to EPICS

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#138]
Lakeshore is not connected.  More diagnostics:

```
In [9]: lakeshore.loop1.settled??                                                                                                                                                             
Type:        property
String form: <property object at 0x7f2dd4622778>
Source:     
# lakeshore.loop1.settled.fget
@property
def settled(self):
    """Is temperature close enough to target?"""
    diff = abs(self.temperature.get() - self.target.get())
    return diff <= self.tolerance.get()

In [10]: lakeshore.loop1.temperature.get()                                                                                                                                                    
Out[10]: -273.15

In [11]: lakeshore.loop1.target.get()                                                                                                                                                         
Out[11]: 25.0

```

So, when lakeshore is not connected, the EPICS support reports a temperature of `-273.15`.  We should trap for that and raise an appropriate exception.

_Originally posted by @prjemian in https://github.com/aps-8id-dys/ipython-8idiuser/issues/118#issuecomment-582037889_

**Comment by qzhang234** [comment]
Maybe write a `if` saying that if the temperature is lower than -270 C then report 'Lakeshore not connected'? There's no way our temperature control in 8-ID-I can even get close to that level

**Comment by qzhang234** [comment]
The new Quantum Northwestern setup, potentially with a future upgrade that will support vacuum environment and temperatures up to 200 C, will hopefully eliminate the need of having to swap between sample environments and temperature readouts. 

With good wishful thinking, closing this issue for now.
