### ISSUE TITLE
Rigaku data is not processing all the frames

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#143]
When collecting data in bluesky (for #46), we do not see all the frames being processed.  Looks like just the first 100 frames.  Very noisy.  Perhaps the wrong number is being written to the metadata file used by processing?

**Comment by prjemian** [comment]
Here is where the `100` number comes:  https://github.com/aps-8id-dys/ipython-8idiuser/blob/35f0a20b429497213d10cb23efb4b45a948978f7/user/Rigaku_Loop.py#L33-L38

**Comment by prjemian** [comment]
Since the Rigaku uses a fixed number of frames, the number we type here should not matter unless this is the only way to get it into the metadata file.

Use `100000` instead.

**Comment by prjemian** [comment]
from SPEC:

```
##############################################
RIGAKU_NUMBER_OF_FRAMES = 100000;  # 100000
RIGAKU_EXPOSURE_TIME_SEC = 19.586e-6;
RIGAKU_EXPOSURE_PERIOD_SEC = RIGAKU_EXPOSURE_TIME_SEC + 0.528e-6;```

**Comment by prjemian** [comment]
These constants *should* be part of the detector's class and `AD_Acquire()` should learn about this.  Later.

**Comment by prjemian** [comment]
So, the `DM_DeviceMixinAreaDetector` class needs routines to set and get the number of frames the detector is to take.  For the lambda, a set, then get will be the same number.  For the Rigaku, it will always return `100000`, regardless of what it was set.

**Comment by prjemian** [comment]
Only the Rigaku will need to override the get method.

**Comment by prjemian** [comment]
Current support now processes all acquired frames which works for the current milestone.  Will refactoir as described for next operations milestone in March.

**Comment by prjemian** [comment]
Wait for #149 before finishing this work.

**Comment by qzhang234** [comment]
This issue has been solved
