### ISSUE TITLE
Control Fly Stage in Bluesky

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#147]
Rigaku detector is commonly used together with the fly stage. There are three macros in SPEC: ```flyscan_setup```, ```flyscan_taxi```, ```flyscan_start```.

I believe ```flyscan_setup``` sets the start and end point of the fly as well as the speed (without actually moving the fly stage), ```flyscan_taxi``` readies the fly stage by moving it to a location slightly before the start point specified in ```flyscan_setup```, and ```flyscan_taxi``` does the actual fly. The plan would proceed to the next line without waiting for the fly to finish so that the acquisition can be performed during the fly, which is the whole point of using the fly stage.

It would be nice if we could add the start/end point and fly speed in the generic Rigaku acquisition plan. We can set the default values of the start/end to be the same in that way if users don't want to do the fly scan they can simply choose to skip those variables when running the Bluesky plan.

What do you think, @sureshnaps @prjemian ?

**Comment by prjemian** [comment]
We have support defined already but it needs testing.

device: https://github.com/aps-8id-dys/ipython-8idiuser/blob/58ad29fc3b0da11255ce6e7eb39d968d021d7507/profile_bluesky/startup/15-spec-config.py#L5-L6

definition: https://github.com/aps-8id-dys/ipython-8idiuser/blob/58ad29fc3b0da11255ce6e7eb39d968d021d7507/profile_bluesky/startup/10-devices.py#L517-L610

**Comment by prjemian** [comment]
Since we have the `flyscan` object (instance of `PSO_TaxiFly_Device()`), we'll need to implement SPEC's `flyscan_setup`.  Then, we already have the other two SPEC macro replacements:

```
         # in a plan, use this 
         yield from abs_set(flyscan, "taxi", wait=True) 
         yield from abs_set(flyscan, "fly", wait=True)
```

We'll write these as part of a new *plan*, once we move to the new file layout (#149).  In the new layout, we'll add a new file: `profile_bluesky/startup/instrument/plans/fly_scans.py`

**Comment by prjemian** [comment]
BTW: the SPEC macro `flyscan_setup` describes what should happen in the `PSO_TaxiFly_Device.stage` method.  Same concept, slightly different implementation.

**Comment by qzhang234** [comment]
I believe we can test the stage any time this week, since the fly stage is connected and the current users are not using it. @sureshnaps Is it correct? @prjemian What time is good for you?

**Comment by qzhang234** [comment]
@prjemian Looks like we already have an issue for fly stage. Shall we continue here?

**Comment by prjemian** [comment]
yes.  Since I forget what is the current state of this code (is it ready for testing?), would you agree we should walk through it first?  (in `profile_bluesky/startup/instrument/plans/fly_scans.py`)

**Comment by qzhang234** [comment]
Sure. However I just noticed `fly_scans.py` is not in the version installed on 8idiuser. Could you confirm?

**Comment by prjemian** [comment]
Right, needs to be created.  Ok, that's where we left it.

**Comment by prjemian** [comment]
completed in duplicate issue #167
