### ISSUE TITLE
ophyd support for new Lambda 2M detector

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#150]
We'll need to create a device for the new 2M detector.  Use standard `ophyd.areaDetector` components as much as possible.

**Comment by prjemian** [comment]
The [ADLambda EPICS database](https://github.com/areaDetector/ADLambda/blob/master/LambdaApp/Db/ADLambda.template) file has the additional components we'll need for the cam plugin.

**Comment by qzhang234** [comment]
Closing this issue for now and focus on getting Lambda 750k to work with Bluesky

**Comment by qzhang234** [comment]
@sureshnaps  Is this still the right EPICS interface for Lambda2M?

**Comment by prjemian** [comment]
Now is the time to implement.

**Comment by qzhang234** [comment]
This issue is solved
