### ISSUE TITLE
Bluesky/DataBroker Test Run

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#153]
Pete and I believe it's a good idea to run Bluesky test using just ```ssh -Y``` (vs. VS Code and Jupyter Lab). We'll use virtual motors for the Tuesday test for now.

<img width="399" alt="Screen Shot 2020-05-01 at 3 40 30 PM" src="https://user-images.githubusercontent.com/48140482/80840814-bf255580-8bc3-11ea-8d33-9f66d0875fe7.png">

**Comment by prjemian** [comment]
What work is needed to finish this issue?

**Comment by qzhang234** [comment]
I think we are done with this
