### ISSUE TITLE
capability to export data from databroker

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#155]
To share data with users and other facilities, we need to provide a site-specific interface to [databroker-pack](https://blueskyproject.io/databroker-pack/index.html), a new development from the DAMA team at NSLS-II.  An example was created in the February beam time this year.  That needs to be adapted to upstream changes in the project and relocated to a repo specific to this beam line.

**Comment by prjemian** [comment]
Here is an example using *databroker-pack* to export data from mongo to a compressed archive file: https://github.com/BCDA-APS/bluesky_instrument_training/blob/e31f3335710499fed031a321eb03ed90d7e50418/export_data.sh

**Comment by qzhang234** [comment]
Here's the link from Pete that unpacks data exported from MangoDB:
https://github.com/BCDA-APS/epics-bluesky-vm/blob/7e9ae898e80f4b484052b265fec90caeb450c9ac/external_data/preparation/README.md

Closing the issue now.
