### ISSUE TITLE
Create Cheatsheet for Bluesky Users

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#158]
I'm creating two Jupyter Notebook cheatsheets for Bluesky users, `align_run.ipynb` for alignment & measurement and `plot_scan.ipynb` for plotting previous scans, located at: 
`/home/beams10/8IDIUSER/.ipython-bluesky/jupyter_cheatsheet`.

Right now I think the biggest problem is the visualization of scan results (equivalent to specr), since we don't know when the Bluesky Browser thing will be ready. However when I tried to run `plot_scan.ipynb` I got errors (See dropdown). Any suggestions?

<details>
<summary> Error message from line 'APS_utils.listruns(num = 40)' in 'plot_scan.ipynb' </summary>
<br>
---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)
<ipython-input-2-222240a07434> in <module>
----> 1 APS_utils.listruns(num = 40)

NameError: name 'APS_utils' is not defined
</details>

**Comment by prjemian** [comment]
Cheatsheet is created, we covered how to replot old scans.  Closing now.  Open new issue as needed.
