### ISSUE TITLE
Image Dump for Wiki Page

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#159]

**Comment by qzhang234** [comment]
<img width="1067" alt="Screen Shot 2020-06-01 at 6 39 00 PM" src="https://user-images.githubusercontent.com/48140482/83465393-67377400-a439-11ea-8826-6a92023eb6a5.png">
<img width="1060" alt="Screen Shot 2020-06-01 at 6 38 24 PM" src="https://user-images.githubusercontent.com/48140482/83465396-67d00a80-a439-11ea-8182-b9a348130c8a.png">

**Comment by qzhang234** [comment]
<img width="1062" alt="Screen Shot 2020-06-01 at 7 01 20 PM" src="https://user-images.githubusercontent.com/48140482/83465694-5affe680-a43a-11ea-8570-88391f1c95f8.png">
<img width="1065" alt="Screen Shot 2020-06-01 at 7 01 34 PM" src="https://user-images.githubusercontent.com/48140482/83465699-5fc49a80-a43a-11ea-8d87-32c1175e5968.png">

**Comment by qzhang234** [comment]
<img width="622" alt="Screen Shot 2020-06-01 at 7 16 01 PM" src="https://user-images.githubusercontent.com/48140482/83466330-605e3080-a43c-11ea-9392-69106acdc688.png">

**Comment by qzhang234** [comment]
<img width="1063" alt="Screen Shot 2020-06-01 at 7 21 43 PM" src="https://user-images.githubusercontent.com/48140482/83466627-48d37780-a43d-11ea-8026-6ee200723c86.png">
<img width="1062" alt="Screen Shot 2020-06-01 at 7 22 05 PM" src="https://user-images.githubusercontent.com/48140482/83466628-4a04a480-a43d-11ea-95fe-d4d487782149.png">

**Comment by qzhang234** [comment]
<img width="1061" alt="Screen Shot 2020-06-01 at 7 24 19 PM" src="https://user-images.githubusercontent.com/48140482/83466712-8d5f1300-a43d-11ea-9454-ea5ec79a6bba.png">

**Comment by qzhang234** [comment]
<img width="1062" alt="Screen Shot 2020-06-01 at 7 44 23 PM" src="https://user-images.githubusercontent.com/48140482/83468107-6e628000-a441-11ea-94dc-4288dfc1b175.png">

**Comment by qzhang234** [comment]
<img width="1062" alt="Screen Shot 2020-06-01 at 7 56 15 PM" src="https://user-images.githubusercontent.com/48140482/83469009-18430c00-a444-11ea-9364-af8a4d57fc6a.png">

**Comment by qzhang234** [comment]
<img width="1062" alt="Screen Shot 2020-06-01 at 8 18 19 PM" src="https://user-images.githubusercontent.com/48140482/83469376-25142f80-a445-11ea-9b0c-62a1efb8c4dd.png">

**Comment by qzhang234** [comment]
<img width="1062" alt="Screen Shot 2020-06-01 at 8 23 40 PM" src="https://user-images.githubusercontent.com/48140482/83469672-f5195c00-a445-11ea-8886-3b38e94ae599.png">
<img width="1062" alt="Screen Shot 2020-06-01 at 8 24 11 PM" src="https://user-images.githubusercontent.com/48140482/83469682-f9457980-a445-11ea-9ff6-d22852ba3914.png">

**Comment by prjemian** [comment]
Can you paste images into the wiki directly?  I use drag/drop from my Windows desktop.  Works from Mac, too?

**Comment by prjemian** [comment]
Close this when you are comfortable that it is completed.

**Comment by qzhang234** [comment]
Drag/drop actually does not work for Wiki on my Mac. I was super annoyed when I found out as well. It works just fine on GitLab.

Shall I create a personal repo outside the current bluesky one for the purpose of dumping images only?

**Comment by prjemian** [comment]
No, this works just fine.
