### ISSUE TITLE
Extracting scaler values and motor positions from Data Broker

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#160]
@prjemian As a continuation of our weekly meeting earlier, could you share some of Dan's wisdom on how this could be done? Thanks!

**Comment by prjemian** [comment]
Looking through the recent [Bluesky tutorials](https://mybinder.org/v2/gh/bluesky/tutorials/master?urlpath=lab), the *Process Tabular Data with Pandas* tutorial has the information needed here.

For a recent scan of `noisy` *vs.* `m1`, this re-plots the scan with pandas, then extracts the data into two array `x` and `y`:

```
header = db[-1]
data = header.table()

data.plot(x="m1", y="noisy")

x = data["m1"].array
y = data["noisy"].array
```
