### ISSUE TITLE
Plot 2D Scan from Bluesky

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#161]
@prjemian This may be a very short issue. Basically if the capacity is already there a quick demo will suffice.

**Comment by prjemian** [comment]
The 2D scan that moves two positioners over all points in a 2-D array, reading from one or more detectors at each point is called [`bp.grid_scan`](https://blueskyproject.io/bluesky/generated/bluesky.plans.grid_scan.html?highlight=grid_scan).  In the `bec` (BestEffortCallback), there is a LiveGrid to plot such data.

**Comment by prjemian** [comment]
Example shown by creating a random number generator as a detector, that updates when m1 or m2 is moved.

![Clipboard01](https://user-images.githubusercontent.com/2279984/83558695-05c6e200-a4d9-11ea-825b-a30bd378c31b.jpg)

**Comment by prjemian** [comment]
Note: I expected the plot to update at every motor position.  The plot, when I scanned this time, showed the first position but did not update all positions until the scan was complete.  Might be some setting on my system.  But the demo still shows the final result and the command used to run the scan.
