### ISSUE TITLE
Cleaning Up Output from AD_Acquire

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#172]
There are three changes I would like to propose to AD_Acquire:

1. In Bluesky, `AD_Acquire` is executed every time an XPCS acquisition is taken. It automatically plots five figures: pind1 vs. time, pind2 vs. time, Atten1 vs. time, Atten2 vs. time, Timebase vs. time (See screenshot attached)

None of these PVs are the ones we want to monitor during a measurement and I can imagine that it could be quite a burden to the run engine if we run 5000 acquisitions, which would mean 25000 lines in 5 Matplotlib interfaces. I therefore propose that we remove all of them. 

2. The screen output of AD_Acquire is way too much. There are essentially only three things we need on the screen: data folder name with full path (/home/8-id-i/ ...), time of the day, and maybe the name of the q map file. We could always add more if we need to debug things, but there is no reason to overwhelm the screen for general users.

3. Per item 2, I don't think it is necessary to add the run ID at the end of the scan as the users can't use it right now (see screenshot attached) and won't be able to use it with Rigaku as most of experiment conditions requires hundreds or thousands of repeats. Users won't go into Data Broker to figure out what is wrong with an acquisition; they'll simply exclude the acquisition from the averaging.

This time I include Suresh and Eric as well because I would like a consensus from everyone. What's your suggestion, @ericmdufresne @sureshnaps ?

<img width="819" alt="Screen Shot 2020-06-18 at 5 16 23 PM" src="https://user-images.githubusercontent.com/48140482/85077296-8fd4a300-b187-11ea-9cbc-e6b5f42c5411.png">
<img width="766" alt="Screen Shot 2020-06-18 at 5 32 03 PM" src="https://user-images.githubusercontent.com/48140482/85078252-a54acc80-b189-11ea-949f-411ce53a5dfc.png">

**Comment by sureshnaps** [comment]
It seems fine. One thought is, AD_acquire will do lambda and other slow measurements as well. Leave it as is, clone it and call it AD_acquire_fast or something and then make that do what you propose.

**Comment by prjemian** [comment]
1. `bec.disable_plots()` to stop the plots, then later `bec.enable_plots()` to start plotting again

**Comment by qzhang234** [comment]
@sureshnaps That's right, however even for lambda we don't need pind1, pind2, atten1, atten2 and  time base, right? Also I think item 2 is still valid regardless of which detector we run.

@prjemian Thank you for the tip! I'll add it to bp_comm202006.py.

**Comment by prjemian** [comment]
2. Most of the output is from `logger.info()`.  We can change these to `logger.debug()` and then `logger.setLevel(logging.INFO)`.  Still, we might need to make more adjustments.  Perhaps even comment-out specific `logger.debug()` and `logger.info()` lines.

**Comment by prjemian** [comment]
1. We can change the signals we record during a scan. Not sure if we can have zero detectors, have not tried that yet.  Might need at least one "detector" signal.

**Comment by qzhang234** [comment]
@prjemian 
1. `logger.debug()` and `logger.info` sound very nice.
2. I didn't know we could do that. Are the PVs being plotted specified in `AD_Acquire`?

**Comment by prjemian** [comment]
!. Aha!  We only record the `areadet` as the "detector"  The other signals are monitored.  That list is [here](https://github.com/aps-8id-dys/ipython-8idiuser/blob/master/profile_bluesky/startup/instrument/plans/xpcs_acquire.py#L88-L96).  In `AD_Acquire()`.

**Comment by qzhang234** [comment]
Nice. I guess we could comment out everything except temperature, since we need at least one PV? What do you think @prjemian ?

Speaking of temperature, any comment about issue #170 on different thermocouples and lakeshore readings? Please comment over there if you have suggestions

**Comment by prjemian** [comment]
3. This can be done but it is just a bit more syntax.  Remember that `RE(plan())` is a function call in python.  The `RE()` function returns a list of the uids for all the runs executed by the `plan()`.  The simple thing to do to suppress printing the output of a function is to assign it to a throwaway variable.   `runlist= RE(plan())`  or even `_ = RE(plan())`.  The list of uids is visual clutter but assigning the return value of `RE` is the type of tedium I don't expect users to enjoy.

**Comment by prjemian** [comment]
About #170, see my [reply](https://github.com/aps-8id-dys/ipython-8idiuser/issues/170#issuecomment-646300710).

**Comment by prjemian** [comment]
What's the chance we comment out most logger lines today but want some of them on a later date?

**Comment by qzhang234** [comment]
Pretty high I would say

**Comment by qzhang234** [comment]
Also I think `_ = RE(plan())` is very elegant. But this suppresses all print-to-screen, right?

**Comment by prjemian** [comment]
`_ = RE(plan())` only gathers the return value (the list of uids).  Any other `print()` or `logger...` statements will not be effected.

**Comment by qzhang234** [comment]
Ah. Thanks for letting me know. 
So we still want to suppress some of the `print()` or `logger.info`, right? 
I'll get rid of the `print()` I added in `AD_Acquire` later

**Comment by prjemian** [comment]
For loggers, we *could* create set a global variable that we'll use to control logging when the global takes a certain value.  That is in addition to setting the logger level, via `logger.setLevel(logging.INFO)` or such.  But that's additional code that adds no other value.  Better to stick to controls via logger level.

**Comment by prjemian** [comment]
As some say, a diagnostic `print()` was valuable at one time.  Convert it to `logger.debug()` and then set the logger logger level to INFO or above and the `logger.debug` won't print.

**Comment by qzhang234** [comment]
@prjemian I did `_ = RE(my_plan())` and the list of run IDs at the end of the scan went away. However, I added `logger.setLevel(logging.INFO)` in my function but all the lines starting with a D are still getting printed out. Any suggestions?

<img width="867" alt="Screen Shot 2020-06-20 at 11 47 57 PM" src="https://user-images.githubusercontent.com/48140482/85216964-b0038e00-b350-11ea-9075-b62d32984067.png">

**Comment by prjemian** [comment]
It seems the logging level can be controlled for each module (python file) that is imported.  To apply this overall, need to change it before logging is first started.  Here is that place: https://github.com/aps-8id-dys/ipython-8idiuser/blob/c02c3bff81244f4ed6bd7fc359fc05531cca4979/profile_bluesky/startup/instrument/session_logs.py#L31

This is the place to change: either `logger.setLevel(logging.INFO)` or `logger.setLevel(logging.WARNING)`

**Comment by prjemian** [comment]
Slight revision.  *Before* logging is started:  https://github.com/aps-8id-dys/ipython-8idiuser/blob/c02c3bff81244f4ed6bd7fc359fc05531cca4979/profile_bluesky/startup/instrument/session_logs.py#L26-L31

Change to this (adds `level` attribute when calling `stdlogpj.standard_logging_setup()`):

```
logger = stdlogpj.standard_logging_setup(
    "bluesky-session", 
    "ipython_logger",
    level= logging.INFO,
    maxBytes=1*MB, 
    backupCount=9)
logger.setLevel(logging.DEBUG)
```

See the source for that here: https://github.com/prjemian/stdlogpj/blob/master/src/stdlogpj/stdlog.py#L26

**Comment by prjemian** [comment]
You can comment-out that last `logger.setLevel(logging.DEBUG)` if you wish.

Explanation:
The call to `stdlogpj.standard_logging_setup()` defines the way loggers will be created for each module that uses logging.  To make them less noisy, use `logging.INFO` or [higher](https://docs.python.org/3/howto/logging.html).

The last line (you can comment it if you wish), only sets the logging level on the console session, not on any other module.  This [StackOverflow post](https://stackoverflow.com/questions/38537905/set-logging-levels) has a brief discussion on this topic.

**Comment by prjemian** [comment]
This GitHub issue is a good example of the need to create separate, single-topic issues.  It becomes easier to separate the conversations and determine if all questions have been answered.

Are all questions answered?

**Comment by qzhang234** [comment]
Yes, all questions are answered. Closing the issue now.

**Comment by qzhang234** [comment]
@prjemian I noticed that all the notification from Debug level are still there after I implemented the lines you instructed. 

Any suggestions?

Also actually if we could remove the lines that say `New stream` that would be nice too.

<details>
<summary> Screen Output </summary>

```

Transient Scan ID: 8117     Time: 2020-06-25 23:50:09
Persistent Unique Scan ID: '74ed53aa-26aa-4142-b809-0c0839f8baf8'
I Thu-23:50:09 - DM workflow kickoff done
I Thu-23:50:09 - b'id=57e3863a-fde9-4d46-bafc-2deef6d154e8 owner=8idiuser status=pending startTime=1593147009.49 startTimestamp=2020/06/25 23:50:09 CDT \n'
New stream: 'baseline'
New stream: 'aps_current_monitor'
New stream: 'Timebase_monitor'
New stream: 'pind1_monitor'
New stream: 'pind2_monitor'
New stream: 'Atten1_monitor'
New stream: 'Atten2_monitor'
New stream: 'pid1_controlled_value_monitor'
New stream: 'pid1_final_value_monitor'
New stream: 'primary'                                                                                                                
+-----------+------------+
|   seq_num |       time |
+-----------+------------+
|         1 | 23:50:12.9 |
D Thu-23:50:13 - after count()
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/L054_Air_att00_0009/L054_Air_att00_0009_0001-100000.hdf
+-----------+------------+
generator repeat_acq ['74ed53aa'] (scan num: 8117)
I Thu-23:50:13 - DM workflow kickoff starting: analysis:True  file:/home/8-id-i/2020-2/comm202006/L054_Air_att00_0009/L054_Air_att00_0009_0001-100000.hdf
L054_Air_att00_0010
I Thu-23:50:13 - AD_Acquire starting
I Thu-23:50:13 - file_path = /home/8-id-i/2020-2/comm202006/L054_Air_att00_0010/
I Thu-23:50:13 - calling full_acquire_procedure()
D Thu-23:50:13 - before update_metadata_prescan()
I Thu-23:50:13 - detNum=46, det_pars={'ccdHardwareColSize': 512, 'ccdHardwareRowSize': 1024, 'ccdxsense': 1, 'ccdzsense': 1, 'harmonic': 1, 'dpix': 0.076, 'saturation': 3, 'adupphot': 1.0, 'efficiency': 1.0, 'gain': 1, 'blemish': 1, 'flatfield': 0, 'distortion': 0, 'parasitic': 0, 'lld': 0, 'manufacturer': 'RIGAKU500K_NoGap'}
D Thu-23:50:13 - after update_metadata_prescan()
D Thu-23:50:13 - supplied metadata = {'ARun_number': 'L054_Air_att00_0010', 'plan_args': {'detector_name': 'rigaku', 'acquire_time': 0.1, 'acquire_period': 0.11, 'num_images': 100000, 'file_name': 'L054_Air_att00_0010', 'submit_xpcs_job': 'True', 'path': '/home/8-id-i/2020-2/comm202006/'}}
D Thu-23:50:13 - file_name = L054_Air_att00_0010
D Thu-23:50:13 - file_path = /home/8-id-i/2020-2/comm202006/L054_Air_att00_0010/
D Thu-23:50:13 - metadata = {'file_name': 'L054_Air_att00_0010', 'file_path': '/home/8-id-i/2020-2/comm202006/L054_Air_att00_0010/', 'ARun_number': 'L054_Air_att00_0010', 'plan_args': {'detector_name': 'rigaku', 'acquire_time': 0.1, 'acquire_period': 0.11, 'num_images': 100000, 'file_name': 'L054_Air_att00_0010', 'submit_xpcs_job': 'True', 'path': '/home/8-id-i/2020-2/comm202006/'}}
I Thu-23:50:13 - scaler should be autocounting now
D Thu-23:50:13 - before count()


Transient Scan ID: 8118     Time: 2020-06-25 23:50:13
Persistent Unique Scan ID: '310f9f2a-7e32-4a68-b4a1-51d6a9cd78da'
New stream: 'baseline'
New stream: 'aps_current_monitor'
New stream: 'Timebase_monitor'
New stream: 'pind1_monitor'
New stream: 'pind2_monitor'
New stream: 'Atten1_monitor'
New stream: 'Atten2_monitor'
New stream: 'pid1_controlled_value_monitor'
New stream: 'pid1_final_value_monitor'
I Thu-23:50:13 - DM workflow kickoff done
I Thu-23:50:13 - b'id=4901dc79-c753-4beb-a2b2-da26bd320a51 owner=8idiuser status=pending startTime=1593147013.45 startTimestamp=2020/06/25 23:50:13 CDT \n'
New stream: 'primary'                                                                                                                
+-----------+------------+
|   seq_num |       time |
+-----------+------------+
|         1 | 23:50:17.0 |
D Thu-23:50:17 - after count()
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/L054_Air_att00_0010/L054_Air_att00_0010_0001-100000.hdf
+-----------+------------+
generator repeat_acq ['310f9f2a'] (scan num: 8118)
I Thu-23:50:17 - DM workflow kickoff starting: analysis:True  file:/home/8-id-i/2020-2/comm202006/L054_Air_att00_0010/L054_Air_att00_0010_0001-100000.hdf

In [20]: I Thu-23:50:17 - DM workflow kickoff done                                                                                   
I Thu-23:50:17 - b'id=92f9d95f-c9fd-4b9d-8e2c-4cc457601b06 owner=8idiuser status=pending startTime=1593147017.5 startTimestamp=2020/06/25 23:50:17 CDT \n'

```

</details>

**Comment by prjemian** [comment]
I need some hands-on time to figure out how to suppress more of these messages.

**Comment by prjemian** [comment]
The `New stream:` messages come from [a `print()` statement](https://github.com/bluesky/bluesky/blob/bdf2cdd73b971e543459f9182ed1595e134c06d7/bluesky/callbacks/best_effort.py#L151-L158) that is not configurable now.

I'll make a request there to make that configurable (such as with a logger).

**Comment by prjemian** [comment]
`New stream:` is printed by BestEffortCallback table.  The table (and thus the `New stream:` message) can be suppressed using:

    bec.disable_table()

The table prints content like this:

```
+-----------+------------+
|   seq_num |       time |
+-----------+------------+
|         1 | 23:50:12.9 |
+-----------+------------+
```

We could easily not print this table.  It has no apparent value.

**Comment by prjemian** [comment]
For the extra debug lines, I'll look at the more expressive log files in the `.logs/` subdirectory.

**Comment by prjemian** [comment]
In https://github.com/aps-8id-dys/ipython-8idiuser/blob/ee75d6d8382767a4e199a2ec9ed969350476cf15/profile_bluesky/startup/instrument/plans/xpcs_acquire.py#L265-L269

might insert line for `bec.disable_table()` before and `bec.enable_table()` after this line: https://github.com/aps-8id-dys/ipython-8idiuser/blob/ee75d6d8382767a4e199a2ec9ed969350476cf15/profile_bluesky/startup/instrument/plans/xpcs_acquire.py#L268

**Comment by prjemian** [comment]
Would also need to import `bec` in this file:

    from ..framework import bec

**Comment by prjemian** [comment]
Did a bit more research into this.  The goal is to reduce unnecessary output to the console.  The `logger` is responsible for much of the output identified as unnecessary.  The `logger` is configured to write a brief version of each log to the console while writing the full version to the log file.

One extreme method is to eliminate the `logger` output to the console completely.  This command will do that for the remainder of the session.  There is no _undo_:

    logger.handlers.pop(0)

To add an _undo_ feature, instead of the above:

    console_log_writer = logger.handlers.pop(0)

then activity with no console output, then:

    logger.addHandler(console_log_writer )


This would go at the very end of `instrument.collection.py`
