### ISSUE TITLE
Bluesky Demonstration on 06/23

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#174]
Here is a list of items for the weekly Bluesky meeting:

1. Align the beam with Bluesky (since it's first day of the beamtime. There's a `lup` that's already defined. How to change count time by the way?)
2. Demonstrate the current status of Bluesky operation (fly stage, suppressed log, etc.)
3. (Pete) Demonstrate the use of suspender (for debugging purposes when there is no beam);
4. (Pete) Demonstrate how to create a dedicated class for temperature control of the fly stage;

**Comment by prjemian** [comment]
1. `scaler.preset_time.put(0.1)` sets count time to 0.1 seconds, in a plan, use `yield from bps.mv(scaler1.preset_time, 0.1)`

**Comment by prjemian** [comment]
2. did not do this today

**Comment by prjemian** [comment]
4. https://github.com/aps-8id-dys/ipython-8idiuser/issues/170#issuecomment-648306659 and https://github.com/aps-8id-dys/ipython-8idiuser/blob/master/profile_bluesky/startup/instrument/devices/epid.py

**Comment by prjemian** [comment]
3. Discussed the Bluesky equivalent of the `check_beam` macro in both our [instrument package](https://github.com/aps-8id-dys/ipython-8idiuser/blob/master/profile_bluesky/startup/instrument/devices/shutters.py#L33-L34) and the [Bluesky documentation on suspenders](https://blueskyproject.io/bluesky/state-machine.html#built-in-suspenders).

Also discussed how to **not** load this suspender (put a comment on this line: `RE.install_suspender(suspend_APS_current)`)

**Comment by qzhang234** [comment]
All goals on this issue have been cleared. Closing it now.
