### ISSUE TITLE
large .bin files slow to robocopy

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#175]
as reported in #173:

> ... the large number of job failures on DM Workflow is due to the fact that the .bin files are too large so DM timed out waiting for .bin file to show up on /home/8-id-i-stage. The files are still transferred by robocopy, it just took longer. However this seems to be a limitor on performance because if the sparsification is a lot faster than robocopy and the files keep piling up, eventually it will fill up the SSD and crash the workflow. Anyway we could improve that transfer speed or get NX web to run on Rigaku PC so that it can save directly to /home/8-id-i?

**Comment by qzhang234** [comment]
Suresh installed a new drive, /home/8ididata. Hopefully that will solve the problem. Closing the issue now.
