### ISSUE TITLE
create NeXus file from specific dataset

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#176]
* slides: https://docs.google.com/presentation/d/1ScpMhGMGeflRdeUS4gJLV9U04sAc91huPLLBDWQC_9c/edit?usp=sharing
* data dir: [2:42 PM] Zhang, Qingteng
    /net/wolf/data/xpcs8/2020-2/comm202006/F020_D100_att02_35p00C_0002 (shutter problem in 0001 file)
* results dir: /net/wolf/data/xpcs8/2020-2/comm202006/cluster_results/F020_D100_att02_35p00C_0002_0001-100000.hdf

**Comment by prjemian** [comment]
[F020_D100_att02_35p00C_0002_0001-100000.zip](https://github.com/aps-8id-dys/ipython-8idiuser/files/4842710/F020_D100_att02_35p00C_0002_0001-100000.zip)

as prepared from current code base: https://git.aps.anl.gov/jemian/xpcs-nexus-8idi

**Comment by dylanmcreynolds** [comment]
Slightly orthogonal, is that work needs to be done to create an ingestor to consume this file. There has been a lot of talk about creating a schema for "projections", which can help us define a mapping between something like NeXuS and objects in the event model. There are various proposals that a quite similar. 
https://github.com/bluesky/event-model/pull/130
https://github.com/bluesky/event-model/pull/179

Currently, we don't know what will be implemented, but I think that something like 179 could be used and if something different comes out of all of this, it won't be too much work to adjust.

**Comment by prjemian** [comment]
BES Pilot Project is on this now, closing here.
