### ISSUE TITLE
Protocol for Turning On Bipolar Power Supply for Lakeshore

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#177]
Dear All:

This might be a known and solved issue (as I can surely recall that Suresh has taught me this more than once), but I noticed that the bipolar power supply is not running, and as a result there's no current nor voltage going through the Peltier so the temperature feedback loop is not working. I recall that Suresh mentioned that we need to click the reset button a few times (or some magic similar to that) to get the power supply started. @sureshnaps @ericmdufresne Could you comment on this? 

Also I believe @prjemian and I have everything sorted out on the Bluesky end. As long as the Peltier is running we should be able to control the temperature using Bluesky.

Thanks,

QZ

<img width="1011" alt="Screen Shot 2020-06-24 at 2 09 19 PM" src="https://user-images.githubusercontent.com/48140482/85621963-c0a35500-b62b-11ea-9ad3-b56acd9cf7e2.png"> 

<img width="1294" alt="Screen Shot 2020-06-24 at 2 34 45 PM" src="https://user-images.githubusercontent.com/48140482/85621956-bd0fce00-b62b-11ea-8674-d768eb14c3b8.png">

**Comment by ericmdufresne** [comment]
Push the enable button on the Kepco.
If this doesn't work, push reset than enable.
Eric

________________________________

**Comment by sureshnaps** [comment]
I had to reset the NI GPIB to serial converter. Since kepco turned off somehow, NI unit stopped communicating, it is ok now.

**Comment by qzhang234** [comment]
I confirmed that the problem is solved. I can control the temperature simply by doing `mov T_SET 30` and I can see `T_A` changing. Closing the issue.

![Uploading Screen Shot 2020-06-24 at 4.57.46 PM.png…]()
