### ISSUE TITLE
`tolerance` and `wait_until_settled` for Fly Stage/PID Temp Ctrl?

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#178]
@prjemian 

I noticed that these lines in the user plan definitely would not work. I can replace `target` with `bps.mov`, but what's the method under PID class for `tolerance` and `wait_until_settled`?

Thanks,

QZ

<img width="1051" alt="Screen Shot 2020-06-24 at 11 02 24 PM" src="https://user-images.githubusercontent.com/48140482/85651963-02092400-b66f-11ea-9b5b-533ab1f3a7fa.png">

**Comment by prjemian** [comment]
Good point.  I do not believe the `epid` record has the concept of _settled_ so these two methods must be built.  We could again create a special subclass of `EpidRecord` that provides these two methods (`settled()` and `wait_until_settled()`) and the supporting attribute `tolerance`.

**Comment by prjemian** [comment]
I do not see such terms in the [documentation](https://cars9.uchicago.edu/software/epics/epidRecord.html) for the `epid` record.

**Comment by prjemian** [comment]
I propose these changes, in file `epid.py`, add:

```
from ophyd import Signal
```

then

```
class WaitingEpidRecord(EpidRecord):

    tolerance = Component(Signal, kind="omitted", value=1)  # override in subclass

    @property
    def settled(self):
        """Is following_error within tolerance?"""
        return abs(self.following_error.get()) <= self.tolerance.get()

    def wait_until_settled(self, timeout=None, timeout_fail=False):
        """
        plan: wait for controller signal to reach setpoint within tolerance
        """
        # see: https://stackoverflow.com/questions/2829329/catch-a-threads-exception-in-the-caller-thread-in-python
        t0 = time.time()
        _st = DeviceStatus(self.following_error)

        if self.settled:
            # just in case following_error already within tolerance
            _st._finished(success=True)
        else:
            started = False
    
            def changing_cb(*args, **kwargs):
                if started and self.settled:
                    _st._finished(success=True)
    
            token = self.following_error.subscribe(changing_cb)
            started = True
            report = 0
            while not _st.done and not self.settled:
                elapsed = time.time() - t0
                if timeout is not None and elapsed > timeout:
                    _st._finished(success=self.settled)
                    msg = f"PID loop '{self.name}' Timeout after {elapsed:.2f}s"
                    msg += f", target {self.controlled_value .get():.2f}"
                    msg += f", now {self.final_value.get():.2f}"
                    print(msg)
                    if timeout_fail:
                        raise TimeoutError(msg)
                    continue
                if elapsed >= report:
                    report += self.report_interval_s
                    msg = f"Waiting {elapsed:.1f}s"
                    msg += f" to reach {self.controlled_value.get():.2f}"
                    msg += f", now {self.final_value.get():.2f}"
                    print(msg)
                yield from bps.sleep(self.poll_s)

            self.following_error.unsubscribe(token)
            _st._finished(success=self.settled)

        self.record_signal()
        elapsed = time.time() - t0
        print(f"Total time: {elapsed:.3f}s, settled:{_st.success}")


pid1 = WaitingEpidRecord("8idi:pid1", name="pid1", labels=["pid",])
pid2 = WaitingEpidRecord("8idi:pid2", name="pid2", labels=["pid",])
```

But note that `target` and `setpoint` attributes are not available with an `EpicRecord` (or `WaitingEpidRecord`) object.  So, other plans which call these controls might need to be modified.

**Comment by prjemian** [comment]
Note: I copied and modified the methods above from the Lakeshore controls.

**Comment by qzhang234** [comment]
Nice. By the way do we want to add `target` there as well, just for completeness? 

Also is the usage of `target`, `tolerance` and `wait_until_settled` the same as Lakeshore?

**Comment by prjemian** [comment]
The `target` attribute (used by the Lakeshore) is the same as the `controlled_value` declared in the `EpidRecord` support.  So, no, we should not add a duplicate `Component` for this same PV.  Rather, we should change our plan code instead.  Also add a note that the plan expects an object which is a subclass of `apstools.devices.EpidRecord()` rather than `apstools.devices.ProcessController()`.

**Comment by prjemian** [comment]
The names in the `EpidRecord()` were chosen to match the documentation.  The names in the `ProcessController` were chosen to match common usage.  _Vive la différence!_

**Comment by qzhang234** [comment]
Definitely.

So still use bps.mov to change the target temperature of PID?

**Comment by prjemian** [comment]
Yes.  `yield from bps.mv(pid1.controlled_value, 2500)`

**Comment by prjemian** [comment]
Yikes!  ` yield from bps.mv(pid1.controlled_value, 25.00)`

**Comment by prjemian** [comment]
Ha!

**Comment by qzhang234** [comment]
Let me add it to the user plan template and give it a quick spin. If it works as expected I'll close the issue

**Comment by qzhang234** [comment]
@prjemian I made the change in `epid.py` and restarted bluesky but I don't see the attribute `tolerance`  under `pid1`. Maybe `epic.py` is not loaded upon startup?

Also for the syntax, should I simply do 
`yield from bps.mv(pid1.tolerance, 0.1)` 
and 
`yield from pid1.wait_until_settled(timeout=200)` 

Last question, more of a basic python thing: I see that in epid.py, for class `WaitingEpidRecord`, you first defined attribute `tolerance` (class: Component) and then defined functions `settled` and `wait_until_settled` using decorator `@property`. Does it mean that `tolerance`, `settled` and `wait_until_settled` will all show up under object `pid1` as attributes?

Thanks,


<img width="884" alt="Screen Shot 2020-06-25 at 1 48 27 PM" src="https://user-images.githubusercontent.com/48140482/85780783-9b295080-b6ea-11ea-9f93-06cb5a2c6832.png">

**Comment by prjemian** [comment]
Did you change these two definitions at the bottom of `epid.py`?

```
pid1 = WaitingEpidRecord("8idi:pid1", name="pid1", labels=["pid",])
pid2 = WaitingEpidRecord("8idi:pid2", name="pid2", labels=["pid",])
```

With these changes, then, yes, you should find `tolerance`, `settled` and `wait_until_settled` as attributes of `pid1`.

**Comment by qzhang234** [comment]
@prjemian Ah. I changed the class names now as you suggested, but now I'm getting error message on the screen which I believe comes from the attribute conflict between the old class and the new class.

Should I just comment out `T_A` and `T_SET` or change `.current_value` to `.controlled_value`?


<details>
<summary> </summary>

```

I Thu-14:03:12 - /home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/devices/lakeshore.py
[TerminalIPythonApp] WARNING | Unknown error in handling startup files:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/IPython/core/shellapp.py in _exec_file(self, fname, shell_futures)
    350                                                  self.shell.user_ns,
    351                                                  shell_futures=shell_futures,
--> 352                                                  raise_exceptions=True)
    353         finally:
    354             sys.argv = save_argv

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/IPython/core/interactiveshell.py in safe_execfile(self, fname, exit_ignore, raise_exceptions, shell_futures, *where)
   2720                 py3compat.execfile(
   2721                     fname, glob, loc,
-> 2722                     self.compile if shell_futures else None)
   2723             except SystemExit as status:
   2724                 # If the call was made with 0 or None exit status (sys.exit(0)

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/IPython/utils/py3compat.py in execfile(fname, glob, loc, compiler)
    166     with open(fname, 'rb') as f:
    167         compiler = compiler or compile
--> 168         exec(compiler(f.read(), fname, 'exec'), glob, loc)
    169 
    170 # Refactor print statements in doctests.

~/.ipython-bluesky/profile_bluesky/startup/00-instrument.py in <module>
      4 """
      5 
----> 6 from instrument.collection import *
      7 
      8 # show_ophyd_symbols()

~/.ipython-bluesky/profile_bluesky/startup/instrument/collection.py in <module>
     12 
     13 from .framework import *
---> 14 from .devices import *
     15 from .plans import *
     16 from .utils import *

~/.ipython-bluesky/profile_bluesky/startup/instrument/devices/__init__.py in <module>
     18 from .epid import *
     19 from .fly import *
---> 20 from .lakeshore import *
     21 from .motors import *
     22 from .preamps import *

~/.ipython-bluesky/profile_bluesky/startup/instrument/devices/lakeshore.py in <module>
    150 # QZ changed on 06/23
    151 T_SET = pid1.final_value
--> 152 T_A = pid1.current_value

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/ophyd/device.py in __getattr__(self, name)
   1195         # Components will be instantiated through the descriptor mechanism in
   1196         # the Component class, so anything reaching this point is an error.
-> 1197         raise AttributeError(name)
   1198 
   1199     def _instantiate_component(self, attr):

AttributeError: current_value

```

</details>

**Comment by prjemian** [comment]
change `.current_value` to `.controlled_value`

**Comment by prjemian** [comment]
Close if this work is complete.
