### ISSUE TITLE
Disabling Bluesky Hang Due To Beamline Current Monitor

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#179]
I think it would be a good idea to disable any trip in Bluesky caused by monitoring of the beamline status because if there's something like beam dump happening during the acquisition, we would much rather figure it out by looking at the data instead of wasting the entire overnight scan. What do yo think, @prjemian ?

**Comment by prjemian** [comment]
That's your call.  Same thing in SPEC (no `check_beam` macro, or at least it does nothing)?

**Comment by qzhang234** [comment]
Ah. Is that the same `suspender` you showed us on Tuesday?

**Comment by sureshnaps** [comment]
This should be more deterministic. We need not check for ring currents. We can check for the hardware signal that feeds into a Digital I/O, more robust than just a PV from the pv gateway.

**Comment by qzhang234** [comment]
I agree with Suresh. Are any of those implemented in the Bluesky right now, Pete?

**Comment by prjemian** [comment]
Probably not implemented now.  Type

`RE.suspenders`

to confirm.  If the list is empty, no suspenders installed.

**Comment by prjemian** [comment]
> [Is that the same `suspender` you showed us on Tuesday?](https://github.com/aps-8id-dys/ipython-8idiuser/issues/179#issuecomment-649675955)

Yes.

**Comment by qzhang234** [comment]
@prjemian I disabled the line `RE.install_suspender(suspend_APS_current)` in `/instruments/devices/shutter.py` and restarted bluesky. There's still another suspender installed, but I think this corresponds to the shutter at the I hutch? If that is true I believe it's Ok to leave it as it is.

Please confirm so that I can close the issue.

Thanks

Here's the output from `RE.suspenders`. 

<details>
<summary> Screen Output </summary>

```

In [1]: RE.suspenders                                                                                                      
Out[1]: (SuspendWhenChanged(EpicsSignalRO(read_pv='PA:08ID:STA_D_SDS_OPEN_PL.VAL', name='pss_d_shutter_open_chain_A', parent='pss', value=1, timestamp=1593024486.020213, auto_monitor=False, string=True), sleep=0, pre_plan=None, post_plan=None,tripped_message=D station shutter changed.  This affects whether or not I station can take beam and whether simulators are used.  Resume is not allowed from this condition. You are strongly advised to exit and restart the bluesky session.),)

In [2]:    

```

</details>

**Comment by prjemian** [comment]
Exactly.  I believe you want this.  

It guards when you start a session with this shutter open.  Then, you are configured to talk with certain upstream hardware directly.  If the shutter closes, you should not continue to operate that hardware.  This protects you from adjusting that hardware if the shutter closes.

**Comment by prjemian** [comment]
Should also remove/comment the log message:

```
I Tue-09:53:30 - /home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/devices/shutters.py
I Tue-09:53:30 - Installing suspender for low APS current.
```

**Comment by qzhang234** [comment]
Please let me know when this is done so that I can test and close the issue

**Comment by prjemian** [comment]
done

**Comment by qzhang234** [comment]
Did you change it in the local version on /home/beams/8IDIUSER?

**Comment by prjemian** [comment]
yes, see these changes b3c37322e1fd3
