### ISSUE TITLE
Why default of None in AD_Acquire()?

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#185]
Looking at recent code changes at the instrument, this change uses default values of `None` for two keyword arguments (kwargs).

![Clipboard01](https://user-images.githubusercontent.com/2279984/85932738-432e4d80-b894-11ea-9a0e-6ae458fc0c60.jpg)

Usually, when `None` is the default, there are lines early in the plan to choose appropriate default values for kwargs that are not named by the caller.  Such as:

```
acquire_time = acquire_time or 0.1
acquire_period = acquire_period or 0.11
```

That code is missing.  If the caller fails to provide these kwargs, the plan will raise an exception when `None` is used in place of a floating point number.

**Comment by qzhang234** [comment]
I made that change. It was intentional. This forces users to specify the acquisition time and acquisition period as those numbers will enter the final XPCS result displayed by the GUI. For example I have something like this in my `bp_CPMV.py`:

```

        yield from AD_Acquire(
            rigaku,
            acquire_time=19.00e-6,
            acquire_period=19.00e-6,
            num_images=100000,
            file_name=acq_name,
            submit_xpcs_job=True,
            atten=None,
            path='/home/8-id-i/2020-2/comm202006/',
            md={})


```

**Comment by prjemian** [comment]
A more natural way to force these parameters to be supplied by the caller is to change them from optional (keyword) arguments into required (positional) arguments.  Further, the need to use `None` goes away.  Since these are already the first keyword arguments after the one positional argument, the changes are simple.

The plan would change to:

```
def AD_Acquire(areadet,
               acquire_time,
               acquire_period,
               ...
```

All callers would need to supply the two terms without names:

```
        yield from AD_Acquire(
            rigaku,
            19.00e-6,
            19.00e-6,
            ...
```

**Comment by qzhang234** [comment]
I see. I'll give that a shot. If we define it like this (is this the non-keyword argument by the way?), then the sequence of the arguments also matters, right?

**Comment by prjemian** [comment]
Right.

**Comment by qzhang234** [comment]
@prjemian I thought about defining `num_imges`, `acquire_time` and `acquire_period` as positional arguments, then I realized that XSPA can't change any of those at this moment. So I kept the keyword arguments and added the correct default values.

Please review and decide that if it's Ok to close the issue.


```

def AD_Acquire(areadet=rigaku, 
               acquire_time=19e-6, 
               acquire_period=19e-6, 
               num_images=100000, 
               file_name='A001',
               submit_xpcs_job=True,
               atten=0, 
               path=None, 
               md={}):
    """

```

**Comment by prjemian** [comment]
These are positional parameters now: https://github.com/aps-8id-dys/ipython-8idiuser/blob/92bb37b820593d31aa24a4d65003d401777a1273/profile_bluesky/startup/instrument/plans/xpcs_acquire.py#L25-L33

I'm OK with that.  Assume this is OK for the XSPA, so closing.
