### ISSUE TITLE
add lup plan

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#186]
provide a lineup plan

**Comment by qzhang234** [comment]
I thought we have this already? 

```

In [3]: lup?                                                                                                               
Signature:
lup(
    scaler_name=None,
    motor_name=None,
    pos_start=-0.5,
    pos_stop=0.5,
    num_pts=41,
)
Docstring: <no docstring>
File:      ~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/alignments.py
Type:      function


```

**Comment by prjemian** [comment]
Right.  You added this code.  I created an issue for it.  Usually, code
changes are committed in reference to an issue.  Here, you wanted the
SPEC-like plan.

**Comment by qzhang234** [comment]
I thought this looks as close as it can get to `lup` in Spec?

**Comment by prjemian** [comment]
In `SPEC`, `lup` is a synonym for `dscan`. The corresponding plan in Bluesky is [`rel_scan`](https://blueskyproject.io/bluesky/generated/bluesky.plans.rel_scan.html?highlight=rel_scan#bluesky.plans.rel_scan) (use `bp.rel_scan`).  Your `lup` plan includes specifics for your instrument.

LGTM.

**Comment by prjemian** [comment]
Close if you think this issue is complete.
