### ISSUE TITLE
foemirror.theta stuck after bp.rel_scan

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#199]
I tried aligning the beamline with Bluesky, and I got this really nice ta2fine scan (foemirror.theta). However, when I tried moving to the center using magic `mov foemirror.theta 3199.3` the motor got stuck, and although I can un-stuck it from EPICS (see attached), I can't move it again. 

I'm not sure this is a Bluesky problem or an EPICS problem. Any suggestions, @sureshnaps and @prjemian?

Also what does the white square around the motor setpoint mean?

<img width="620" alt="Screen Shot 2020-07-09 at 12 55 06 AM" src="https://user-images.githubusercontent.com/48140482/87004104-85079f80-c182-11ea-9e49-6ac7e015320f.png">
<img width="427" alt="Screen Shot 2020-07-09 at 1 23 14 AM" src="https://user-images.githubusercontent.com/48140482/87004297-d44dd000-c182-11ea-9699-1fae6ea13b1c.png">

**Comment by prjemian** [comment]
The white square: isn't that the stop button?  This is an IOC issue.

**Comment by qzhang234** [comment]
Oh boy. You still up?

**Comment by qzhang234** [comment]
Also that would be my guess which is why I included Suresh.

**Comment by qzhang234** [comment]
Ok @prjemian I think I now have a better and clearer description of this bug:

- 1. `ta2fine` is a soft motor. The real hard motor is `ta2rotact`, a.k.a. `8ida:m12` (Screenshot attached);
- 2. The white box around `ta2fine` EPICS interface does not have indication on its condition;
- 3. If tweaked by step of 1 (1 is 1 microradian) `ta2fine` may jam occasionally even in EPICS;
- 4. If tweaked by step of 2 `ta2fine` will not jam;
- 5. If moved in Bluesky using `movr foemirror.theta 2`, `ta2fine` will jam the second time `movr` is executed, regardless of step size. This bug is repeatable every time I tried it.

@sureshnaps said we should not play with this motor as it is very upstream (A hutch) and if the hard motor really jams then we have to shut down everything including 8-ID-I and 8-ID-E, so we should be very careful in debugging this, but then again we align this motor every week, so it would be nice to eventually get it fixed. @prjemian What do you think?

<img width="434" alt="Screen Shot 2020-07-09 at 4 05 53 PM" src="https://user-images.githubusercontent.com/48140482/87090768-1a944500-c1fe-11ea-976d-68a7da4d0def.png">

**Comment by prjemian** [comment]
We need to understand exactly what happens to `ta2fine` when `movr foemirror.theta 2` is called.  Who engineered this IOC?  That person could advise us.  Was it Joe Sullivan (@jsullivan-anl)?

Something needs to be adjusted in the ophyd device but maybe the IOC implementation could use some additional protections as well.

**Comment by qzhang234** [comment]
I agree. Maybe @sureshnaps  could provide some more insight on this? Also we'll need Suresh's permission to further investigate this issue as it could be very disruptive to User Op if it goes wrong

**Comment by prjemian** [comment]
Since this works in SPEC and from a GUI yet not in Bluesky, then obvious that it is bluesky that needs to change.  (Nonetheless, there is still probably a low-level bug in the EPICS IOC but maybe we don't have to fix that here.)

**Comment by prjemian** [comment]
@qzhang234 : We'd like to schedule a troubleshooting session for this axis `ta2fine` for Monday afternoon.  Involving @jsullivan-anl and @twalshanl.  Anyone else?

**Comment by prjemian** [comment]
This is a soft motor (sm9) that operates a physical motor (m12).  The calculations make it appear that the only added value of sm9 is a units conversion, no other signals are involved.  Can the beam line do the necessary alignment with only the physical motor (m12)?  Why is sm9 necessary?

**Comment by prjemian** [comment]
Hypothesis:  Since this is a soft motor used to operate a physical motor, is it possible there exists a race condition so that GUI controls (working within human reaction times) succeed while programmatic controls (working with shorter times between actions) fail?  Maybe the addition of small sleep interval was added to the SPEC controls to make this work without error?

**Comment by qzhang234** [comment]
That could be the case. It would be nice to scan the real motor and see if the same problem occurs or not

**Comment by prjemian** [comment]
While diagnosing, we got the motor record into `Moving` state and found the physical motor record was in the `Pause` state.  We set it to `Go` and it is back in `Pause` again.  Seems to be left that way after the motor was moved in bluesky.

**Comment by prjemian** [comment]
When stepping `ta2fine` from GUI screen, this does not happen.  Does Bluesky put the motor into `Pause`?

**Comment by prjemian** [comment]
The soft motor support for ta2fine was set to write the motor's SPMG field for emergency stop.  This should be the motor's stop (STOP) field.  We tested this and it worked correctly.

**Comment by prjemian** [comment]
FYI: when 1 is written to the SPMG field, the motor is PAUSEd.

**Comment by prjemian** [comment]
@klauer:  When a motor is moved from ophyd, is a STOP sent to the motor at the end of the move?  We are trying to understand why this (soft) motor was receiving a stop command for a motion.

**Comment by klauer** [comment]
Failure handling: https://github.com/bluesky/ophyd/blob/b1d258a36c974013b6e3ac8ee7112ed876b7653a/ophyd/status.py#L605-L608

**Comment by prjemian** [comment]
Thanks!  That explains it.  The failure happened since the `.SPMG` field was used, rather than the `.STOP` field so this paused the motor at the end of the first move.  The problem happened with the next attempt to move.

**Comment by prjemian** [comment]
@qzhang234 : Close this issue when you are satisfied it is complete.
