### ISSUE TITLE
'UFXC_align_mode' and UFXC_data_mode' in Bluesky

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#200]
I noticed that Bluesky doesn't have the `UFXC_align_mode` and `UFXC_data_mode` as defined in Spec. The former lets you control the fast shutter in I hutch using `sb()` and `bb()`, while the latter lets XSPA control the shutter and is/should be part of `select_RIGAKU`. I've attached the 3-line source code in Spec for both. 

Maybe it's already implemented in Bluesky and I just simply don't know how to run it?

<details>
<summary> UFXC_align_mode in Spec</summary>

```

408.SPEC8IDI> prdef UFXC_align_mode 

# /home/beams/8IDIUSER/local_macros/CCD_macros/UFXC_shutter_logic.mac
def UFXC_align_mode '
	epics_put("8idi:softGlueC:AND-4_IN2_Signal","1UFXC");
	shutteroff;
	printf("Shutter will remain OPEN for alignment if **showbeam** is called\n");
'

```
</details>

<details>
<summary> UFXC_data_mode in Spec </summary>

```

410.SPEC8IDI> prdef UFXC_data_mode 

# /home/beams/8IDIUSER/local_macros/CCD_macros/UFXC_shutter_logic.mac
def UFXC_data_mode '
	epics_put("8idi:softGlueC:AND-4_IN2_Signal","UFXC");
	shutteroff;
	printf("Shutter will be controlled by UFXC if shutter is left in the **showbeam** state\n");
'

```
</details>

**Comment by prjemian** [comment]
Need to make an ophyd signal for this PV (`8idi:softGlueC:AND-4_IN2_Signal`) and then can `.put("1UFXC")` to that signal.

**Comment by prjemian** [comment]
Aha!  This is the `shutter_mode` signal (already known): https://github.com/aps-8id-dys/ipython-8idiuser/blob/b3c37322e1fd3639bc592ce824dd662421a0f244/profile_bluesky/startup/instrument/devices/shutters.py#L61-L62

Remember that you will need to import that signal first, such as `from instrument.devices import shutter_mode` and then you can replace the `epics.caput(pv, value)` calls with `yield from bps.mv(shutter_mode, value)`.

BTW: I found this by searching: `git grep AND-4_IN2_Signal`

**Comment by prjemian** [comment]
Checked the code today for instances where `epics.caput` is called.  Only found these:

```
(bluesky_2020_9) jemian@wow ~/.../projects/ipython-8idiuser $ git grep caput
profile_bluesky/startup/spec_support/daemon.sh:            caput 8idi:Reg170 0
profile_bluesky/startup/spec_support/spec_DM_support.py:            logger.debug(f'caput("{self.pv.pvname}", {value})')
profile_bluesky/startup/spec_support/spec_DM_support.py:                        logger.warning("retrying caput(trigger PV, 0) {calls} times```

The first is from a shell script, the other are documentation, not calls.

Checked for `shutter_mode`.  Ignore the `archive` findings.  There a few cases that `.put()` a value.  These could be improved by creating a more intuitive name:

```
(bluesky_2020_9) jemian@wow ~/.../projects/ipython-8idiuser $ git grep shutter_mode
profile_bluesky/startup/instrument/archive/21-signals.py:shutter_mode = EpicsSignal("8idi:softGlueC:AND-4_IN2_Signal", name="shutter_mode")
profile_bluesky/startup/instrument/archive/26-rigaku.py:        shutter_mode.put("UFXC")    # data mode
profile_bluesky/startup/instrument/archive/50-controls.py:    yield from bps.mv(shutter_mode, "1UFXC")    # "align" mode
profile_bluesky/startup/instrument/archive/50-controls.py:    shutter_mode.put("1UFXC")
profile_bluesky/startup/instrument/archive/50-controls.py:    #shutter_mode.put("1UFXC")
profile_bluesky/startup/instrument/devices/rigaku_ufxc.py:from .shutters import shutter_mode, shutter_control, shutter_override
profile_bluesky/startup/instrument/devices/rigaku_ufxc.py:        shutter_mode.put("UFXC")    # data mode
profile_bluesky/startup/instrument/devices/shutters.py:    'shutter_mode',
profile_bluesky/startup/instrument/devices/shutters.py:shutter_mode = EpicsSignal("8idi:softGlueC:AND-4_IN2_Signal", name="shutter_mode")
profile_bluesky/startup/instrument/plans/alignments.py:from ..devices import shutter, shutter_mode, scaler1
profile_bluesky/startup/instrument/plans/alignments.py:    shutter_mode.put("1UFXC")
profile_bluesky/startup/instrument/plans/alignments.py:    #shutter_mode.put("1UFXC")
profile_bluesky/startup/instrument/plans/pv_registers.py:from ..devices import shutter_mode, shutter_override, soft_glue
profile_bluesky/startup/instrument/plans/pv_registers.py:    yield from bps.mv(shutter_mode, "1UFXC")    # "align" mode
profile_bluesky/startup/issue151-demo.ipynb:      "shutter_mode     EpicsSignal                      8idi:softGlueC:AND-4_IN2_Signal
```

**Comment by prjemian** [comment]
@qzhang234 : In SPEC, there is a `shutteroff` macro.  What does that do (`prdef shutteroff`)?  Is this feature (align and data mode selection) specific to the UFXC detector or will it be used by other detectors, too?  (If specific, then we should move this `shutter_mode` signal to the UFXC support.)

**Comment by qzhang234** [comment]
```shutteron``` and ```shutteroff``` actually preceded UFXC. It was commonly used with ```showbeam``` and ```blockbeam```. 

The logic goes (@sureshnaps Please correct me if I'm wrong):

If ```showbeam``` and ```shutteron```, then the detector controls the shutter and closes the shutter when it is not acquiring (Similar to UFXC_data_mode)

If ```showbeam``` and ```shutteroff```, then the detector does not control the shutter and with ```showbeam``` in place, the shutter is always open. This mode is for alignment (similar to UFXC_align_mode) and is the reason why in my cheatsheet I have ```sb``` and ```bb``` manually added.

If ```blockbeam```, the shutter won't open no matter what.

However, I just tested the commands in SPEC, and it doesn't seem like it's doing anything, while ```UFXC_align_mode``` and ```UFXC_data_mode``` controls the shutter just fine
