### ISSUE TITLE
How to specify 1. data folder full path; 2. Q map full path; 3. DM Workflow name at beginning of the cycle?

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#206]
I'm setting up environments to test Bluesky during the shutdown. I would like to start setting up in a new cycle (2020-3) since it is a good change to practice doing everything from scratch.

For the analysis to run properly, we need three components: 

1. Full path for the data folder (containing the raw data and the hdf metadata)
2. Full path for the Q map (usually saved in ```/home/8-id-i/partitionMapLibrary/2020-3```)
3. Name of the workflow (XSPA and Lambda uses different DM Workflow)

Item 1 can be specified as input in ```AD_Acquire``` so it's already solved. I do not know how to change Item 2 in Bluesky. Item 3 is related to issue #180 and later mentioned in #198 but a solution was not found, although it was suggested that it be saved in StrReg somewhere.

My question is: is it possible to also include _Q map name_ and _DM workflow name_ as standard input variables in ```AD_Acquire```? I understand that will make ```AD_Acquire``` very unwieldy, but based on my run experience, we almost never call ```AD_Acquire``` by itself and always have it embedded in some user macro, therefore it would be probably better to have all the Workflow components visible from the top. We can write those variables into corresponding StrReg after ```AD_Acquire``` is called.

@sureshnaps @prjemian Please let me know what you think

**Comment by prjemian** [comment]
There is a string register for the QMAP: (StrReg13) but the local script should set this.

The caller of `AD_Acquire()` should set the `qmap_file` as part of its code _before_ calling `AD_Acquire()`.

**Comment by qzhang234** [comment]
So, to summarize today's discussion:

1. We'll rely on ```select_rigaku``` / ```select_LAMBDA``` for specifying workflow;
2. We'll toggle ```areadet.qmap_file``` to change the q map. Object ```rigaku``` and ```Lambda``` under class ```areadet``` are defined upon startup of Bluesky. The q map will be defined in the user bluesky plan outside ```AD_Acquire```.
3. The data folder definition is fine so we'll leave it as it is.
4. Currently we don't want ```select_rigaku``` and ```select_LAMBDA``` to move detectors, but eventually (after we move back to 4 m and after we fix the EPICS IOC problem for Lambda 750k) we would like to have that option as well.

@sureshnaps could you review this to make sure if these items are accurate? If so @prjemian and I will act on them.

Thanks!

**Comment by sureshnaps** [comment]
> So, to summarize today's discussion:
> 
> 1. We'll rely on `select_rigaku` / `select_LAMBDA` for specifying workflow;
> 2. We'll toggle `areadet.qmap_file` to change the q map. Object `rigaku` and `Lambda` under class `areadet` are defined in the Bluesky startup scripts. The q map will be defined in the user bluesky plan outside `AD_Acquire`.
> 3. The data folder definition is fine so we'll leave it as it is.
> 4. Currently we don't want `select_rigaku` and `select_LAMBDA` to move detectors, but eventually (after we move back to 4 m and after we fix the EPICS IOC problem for Lambda 750k) we would like to have that option as well.
> 
> @sureshnaps could you review this to make sure if these items are accurate? If so @prjemian and I will act on them.
> 
> Thanks!

Yes this is correct.
