### ISSUE TITLE
Prepare Bluesky for Lambda 250K from the DP

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#207]
Discussion from MS Teams:
![Clipboard01](https://user-images.githubusercontent.com/2279984/90540952-8a73e480-e147-11ea-8755-451af5ae5402.png)

**Comment by prjemian** [comment]
[Yesterday 4:26 PM] Narayanan, Suresh
    To run Lambda 250K IOC:

1. ssh to pepper as 8ideuser (U-8-ide) (could be any of the 8idi machines as well)
1. go_lambda (script to ssh to lambda server)
1. cd /home/xspadmin (home dir)
1. start_epics_displays.sh (MEDM)
1. startIOC.sh (it is running on 8ideuser virtual on pepper now)

**Comment by qzhang234** [comment]
It is believed that Keenan has fixed the imm plugin issue for Lambda750k at 8-ID-I. Will resume testing at 8-ID-I after AD_Acquire for Rigaku is fully implemented. Closing this issue for now to avoid distraction.
