### ISSUE TITLE
more about shutter_mode (for Rigaku)

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#212]
In #200, the two modes for `shutter_mode` were defined.  It was determined that `shutteroff` is a no-op so can be removed.  Also, `shutter_mode` is more general than just UFXC, so move (?) that bit of code out of rigaku support and into shutters?

**Comment by prjemian** [comment]
General idea, move `shutter_mode.data_mode()` from detector's stage method into the `alignments.post_align()` method.  Callers should call `post_align()` before `AD_Acquire()`.

**Comment by qzhang234** [comment]
I think it's a good idea to have ```pre_align``` and ```post_align``` include ```UFXC_align_mode``` and ```UFXC_data_mode```, respectively. 

Also per Suresh's comment it would be nice to keep ```UFXC_align_mode``` and ```UFXC_data_mode``` rigaku-specific, but callable from ipython terminal so one doesn't have to roll back to Spec for simple tasks like that. Is this capacity ready to be tested right now, @prjemian ?

**Comment by prjemian** [comment]
We could test the changes of 5dca5e4 now if the beamline is switched to the 212-shutter_mode branch.  But the decision that these mode changes are specific to the UFXC means we should modify that branch further to make them only available to the UFXC.

**Comment by prjemian** [comment]
So, `shutter_mode` should be an attribute of `rigaku`, right?

**Comment by prjemian** [comment]
We just discussed this again.  I'll raise the priority of this so we make sure to move `shutter_mode` to be an attribute of the Rigaku UFXC detector.  That way, the Lambda support cannot change this accidentally.

**Comment by prjemian** [comment]
closed with #219 in 7fbd916
