### ISSUE TITLE
'select_RIGAKU' Timed Out

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#216]
I was testing ```select_RIGAKU``` in Bluesky and I got the following error (see attached). This comes from the fact that the upstream stages are disabled in EPICS, right?

<details>
<summary> Error Message from 'select_RIGAKU' </summary>

In [1]: RE(select_RIGAKU())                                                                                                   
CA.Client.Exception...............................................
    Warning: "Channel write request failed"
    Context: "op=1, channel=8idi:m90.VAL, type=DBR_DOUBLE, count=1, ctx="8idi:m90""
    Source File: ../oldChannelNotify.cpp line 158
    Current Time: Wed Sep 02 2020 10:53:13.249222184
..................................................................
CA.Client.Exception...............................................
    Warning: "Channel write request failed"
    Context: "op=1, channel=8idi:m91.VAL, type=DBR_DOUBLE, count=1, ctx="8idi:m91""
    Source File: ../oldChannelNotify.cpp line 158
    Current Time: Wed Sep 02 2020 10:53:13.250637036
..................................................................

</details>

**Comment by prjemian** [comment]
Yes.  The RunEngine waits for motors to reach their targeted positions.
This is a timeout for two of them.

**Comment by prjemian** [comment]
Not a timeout, write request has been refused by the IOC.
