### ISSUE TITLE
helper.py crashes if there is a decimal in the file name 

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#222]
<img width="773" alt="Screen Shot 2020-09-11 at 7 22 53 PM" src="https://user-images.githubusercontent.com/48140482/92982557-49c86c00-f464-11ea-87d7-a08f75b49613.png">

**Comment by prjemian** [comment]
[`apstools.utils.cleanupText()`](https://apstools.readthedocs.io/en/latest/source/_utils.html#apstools.utils.cleanupText) is the tool to use.

**Comment by qzhang234** [comment]
I clicked on the link but I still don't quite understand the syntax. @prjemian Could you provide an example? 

Thanks!

**Comment by prjemian** [comment]
```
        original = "1. Some text to cleanup #25"
        received = apstools.utils.cleanupText(original)
        expected = "1__Some_text_to_cleanup__25"
```

**Comment by qzhang234** [comment]
Ah. Thank you!!

**Comment by prjemian** [comment]
Was the code changed?  Where is the commit with the changes?
