### ISSUE TITLE
delete the archive directory

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#225]
The `~/.ipython-bluesky/profile-bluesky/startup/archive` directory was created to preserve the instrument directory contents.  Issue #209 should have removed the directory yet it is there on disk now.

**Comment by prjemian** [comment]
Confirmed this directory is not in the repository now so can just delete the directory on disk.  First, confirm by `git pull` on disk.

**Comment by qzhang234** [comment]
Good timing; I was thinking about deleting some of the jupyter stuff I created from the folder. It's time we clean it up a bit.

**Comment by prjemian** [comment]
This folder has now been deleted.
