### ISSUE TITLE
Error message when exiting Bluesky

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#229]
@prjemian I saw this error message when I was restarting Bluesky earlier. Is this concerning?

<details>
<summary> Error message on Bluesky terminal </summary>

```
In [19]: exit()
epicsMutex pthread_mutex_destroy failed: error Device or resource busy

/home/beams/8IDIUSER/bin/bluesky8IDI: line 49: 15543 Segmentation fault      (core dumped) ipython ${IPYTHON_OPTIONS}

```

</details>

**Comment by prjemian** [comment]
Did you have to ^C to finish the exit?

This might be a transient that we do not know how to resolve.  Watch if it happens again.

**Comment by qzhang234** [comment]
I think I just pressed `Enter` and it exited fine. Will close the issue for now and watch if it happens later
