### ISSUE TITLE
Skipping jammed Rigaku measurement and restart run engine?

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#230]
I noticed the same error on the LabView panel when I ran XSPA with Spec. Guess the jamming we saw in #223 two weeks ago is not a Bluesky problem. 

This raises a question: Is there a way to modify Bluesky so that it automatically moves on to the next measurement if XSPA does not respond for more than 60 s (each measurement should take no more than 5 s)?

**Comment by qzhang234** [comment]
One thing I was also thinking: is it possible to send out an email from Bluesky when a scan crashed or hung?

**Comment by prjemian** [comment]
Yes.  See [`EmailNotifications()`](https://apstools.readthedocs.io/en/latest/source/_utils.html?highlight=EmailNotifications#apstools.utils.EmailNotifications).  Here's an example:

```
from apstools.utils import EmailNotifications, run_in_thread
email_notices = EmailNotifications("8idiuser@aps.anl.gov")
email_notices.add_addresses(
    "joe.user@anl.gov",
)

@run_in_thread
def _send_emails(subject, message):
    """send a message from a detached thread so it does not block execution"""
    email_notices.send(subject, message)

# then, when some condition occurs
subject = "Feedback problem"
message = "Feedback is very close to its limits."
if email_notices.notify_on_feedback:
    self._send_emails(subject, message)
```

**Comment by prjemian** [comment]
> Is there a way to modify Bluesky so that it automatically moves on to the next measurement if XSPA does not respond for more than 60 s (each measurement should take no more than 5 s)?

If we can catch the timeout, for sure we can do this.

**Comment by prjemian** [comment]
We might want to catch a sequence of _n_ consecutive jams to make sure we do not retry a hopeless situation.

**Comment by qzhang234** [comment]
Yes. I would say 3 times would be enough.

Also the same Rigaku timeout bug has occurred twice with Bluesky in #223 and once with Spec this week. It's a recurring and reproducible problem. Nakaye doesn't know the source of this so we'll have to do it from our end. Hopefully implementing the Bluesky re-throw will permanently fix this bug.

Also now that I think about this, most of the jam or crash when operating Rigaku/Bluesky can be fixed by simply Ctrl+C and then restart the plan. Maybe this implementation is the last step towards the milestone of one week of continuous Bluesky user operation.

The beam will be down next Monday (09/28) at 8 am and doesn't come back till Thursday 8 am (10/01). In the meantime let's get this done. @prjemian Please let me know if there's anything that I can help.

Thanks!

**Comment by qzhang234** [comment]
The same bug occurred again while running with Spec on 09/27, 11:35 pm. I'm therefore changing the label to 'high priority'.

It looks like our best chance is to run Bluesky for the week of 10/01 - 10/12 with the rethrow capacity implemented.

@prjemian There's no beam till 10/01. Please advise on how we should start working on this. Thanks!

<img width="896" alt="Screen Shot 2020-09-28 at 2 35 04 PM" src="https://user-images.githubusercontent.com/48140482/94477673-d3cc4080-0197-11eb-85e3-b5257fda820e.png">
<img width="887" alt="Screen Shot 2020-09-28 at 2 32 13 PM" src="https://user-images.githubusercontent.com/48140482/94477414-7c2dd500-0197-11eb-91ce-d82ee9dd9348.png">

**Comment by prjemian** [comment]
So, we want to implement a timeout around a call to `yield from AD_Acquire()`.  

If timeout, then:

* send email
* wait for ~5 minutes
* retry up to *n* times
* finally move on to next.

**Comment by qzhang234** [comment]
Just to leave a note that the LabView hang occurred again at 23:33 on 09/29

<img width="888" alt="Screen Shot 2020-09-30 at 12 41 01 PM" src="https://user-images.githubusercontent.com/48140482/94720603-4e24ce00-031a-11eb-90c1-5351e037bcc5.png">
<img width="1218" alt="Screen Shot 2020-09-30 at 12 41 56 PM" src="https://user-images.githubusercontent.com/48140482/94720632-57159f80-031a-11eb-86c1-918cf6860c5f.png">

**Comment by prjemian** [comment]
Commit 2d2d672 should also handle the ReadTimeout problems affecting #233
