### ISSUE TITLE
send emails

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#232]
One thing I was also thinking: is it possible to send out an email from Bluesky when a scan crashed or hung?

_Originally posted by @qzhang234 in https://github.com/aps-8id-dys/ipython-8idiuser/issues/230#issuecomment-699585199_

**Comment by prjemian** [comment]
Yes.  See [`EmailNotifications()`](https://apstools.readthedocs.io/en/latest/source/_utils.html?highlight=EmailNotifications#apstools.utils.EmailNotifications).  (edited) This example is now in the docs:

```python
from apstools.utils import EmailNotifications

SENDER_EMAIL = "8idiuser@aps.anl.gov"
email_notices = EmailNotifications(SENDER_EMAIL)
email_notices.add_addresses(
    "joe.user@anl.gov",
    "instrument_team@aps.anl.gov",
    # others?
)

# then, when some condition occurs
if feedback_limits_approached:
    subject = "Feedback problem"
    message = "Feedback is very close to its limits."
    email_notices.send(subject, message)
```

**Comment by qzhang234** [comment]
@prjemian This email function doesn't seem to be working?
