### ISSUE TITLE
pre_align() not working

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#234]
pre_align() is not opening the shutter.

I believe this issue is related to #212, #213, #219 and #227. In particular, I think pre_align() stopped working after #227 and #213 has a pending push request.

Although we have select_RIGAKU and select_LAMBDA which defines its own shutter control, I think in general we want pre_align and post_align to be independent of the detectors.

**Comment by qzhang234** [comment]
For now I'm rolling back to Spec for the sample alignment

**Comment by prjemian** [comment]
re-investigate after pending PRs (#236 and #213) are merged

**Comment by prjemian** [comment]
PEBKAC
