### ISSUE TITLE
Ophyd device for QNW temperature controller

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#267]
The PV name for the device is `8idi:QNWenv_1`, `8idi:QNWenv_2` and `8idi:QNWenv_3`. Tom Walsh at BCDA wrote the EPICS IOC for it. The screenshot shows the caqtdm screen at 8-ID-I. 

The device is the cornerstone for remote operation at 8-ID-I during Covid and will continue to operate after APS-U.

![image](https://user-images.githubusercontent.com/48140482/128263421-08a19d3e-e628-4760-92a5-9e7d81410350.png)

**Comment by prjemian** [comment]
This is three different instances of the same QNW temperature controller (not a 3-channel controller).

**Comment by prjemian** [comment]
Let's make a working ophyd Device in this repo, then `apstools` can _hoist_ this so it becomes available for any beam line.  Similar to the hoist for [Lakeshore](https://github.com/BCDA-APS/apstools/issues/493) controllers.

**Comment by qzhang234** [comment]
@prjemian Gilberto's new Ophyd also works and the definition is located in `devices`
