### ISSUE TITLE
Implement simulated shutter

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#276]
The key component of Bluesky testing is detector control, however currently `AD_Acquire` controls the real shutter.

With simulated shutter, Bluesky testing can be performed independently of user ops as long as it does not test the same detector the user is using.

**Comment by prjemian** [comment]
See https://apstools.readthedocs.io/en/latest/source/_devices.html?highlight=shutter#apstools.devices.SimulatedApsPssShutterWithStatus

**Comment by qzhang234** [comment]
This issue is solved
