### ISSUE TITLE
get workflow uuid and save to register PV

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#78]
The data workflow (both analysis and transfer) returns an id code (a UUID) in its output.  Scrape that value out and write it into 8idi:StrReg14 (?).

**Comment by prjemian** [comment]
Added a TODO: comment to pinpoint where to implement (and what it looks like): https://github.com/aps-8id-trr/ipython-8idiuser/blob/80f6139f8568db78f2180a541c7a666afd4f6130/profile_bluesky/startup/spec_support/APS_DM_8IDI.py#L218-L219

**Comment by prjemian** [comment]
Note the `id` *is* a [UUID](https://docs.python.org/3.7/library/uuid.html#uuid.uuid4), a random string of hex digits with dash separators.

**Comment by qzhang234** [comment]
I just checked StrReg 14 (workflow UUID) and looks like this is still not saved. Is this issue still relevant? If not I can close it
